language: python
sudo: required
python:
  - '2.7'
install:
  - pip install -r requirements.txt
compiler:
  - gcc
env:
  - TEST_CMSSW_VERSION=CMSSW_10_2_10 SCRAM_ARCH=slc6_amd64_gcc700
before_install:
  - docker pull claria/cvmfs-cms
script:
  - docker run --privileged -e TEST_CMSSW_VERSION=${TEST_CMSSW_VERSION}
                            -e SCRAM_ARCH={SCRAM_ARCH}
                            -c "py.test ./tests"